version: '3'
services:
  api:
    image: "emrahisik/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: "emrahisik/multi-client"
    mem_limit: 128m
    hostname: client
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    image: "emrahisik/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    restart: always
    image: "emrahisik/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"